### ISSUE TITLE
unhandled SNMP errors

### ISSUE THREAD

**Issue by scratchfury** [ytti/corona#8]
If an SNMP device replies, there is no check to make sure the reply is valid.  One such case is when the community string is different.  All the fields get filled with Null and trying to process the data fails like this:

``/usr/local/rvm/gems/ruby-2.4.2/gems/corona-0.1.9/lib/corona/core.rb:165:in `normalize_opt': undefined method `sub!' for SNMP::Null:Class (NoMethodError)``

I figured out a very ugly workaround in snmp.rb by making the change found in the 2nd of the following code blocks:

```ruby
    def mget oids=DB_OID
      result = {}
      begin
```

```ruby
        temp = @snmp.get(oids.map{|_,oid|oid})
        if temp.error_status.to_s != "noError"
          puts "error = " + temp.error_status.to_s
          return
        end
```
```ruby
        @snmp.get(oids.map{|_,oid|oid}).each_varbind do |vb|
```
As you can see, I'm not a Ruby programmer and don't even know where to start on making this code look right.  Can someone take a crack at making this fix?

**Comment by jalmargyyk** [comment]
fixed in release [https://github.com/ytti/corona/tree/v0.1.10](url)
